# Generated by Django 2.2.5 on 2019-10-26 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('target_emotion', models.IntegerField()),
                ('emotion_0', models.FloatField()),
                ('emotion_1', models.FloatField()),
                ('emotion_2', models.FloatField()),
                ('emotion_3', models.FloatField()),
                ('emotion_4', models.FloatField()),
                ('emotion_5', models.FloatField()),
                ('emotion_6', models.FloatField()),
                ('emotion_7', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True, db_column='time')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children_app.Child')),
            ],
            options={
                'db_table': 'result',
            },
        ),
    ]
