# Generated by Django 2.2.5 on 2019-10-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='sessionscore',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='child',
            name='wholescore',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
