# Generated by Django 2.2.5 on 2019-10-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_app', '0002_auto_20191027_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='emojitype',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
