# Generated by Django 2.1.13 on 2019-10-27 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('mp4', models.FileField(blank=True, db_column='mp4', null=True, upload_to='tale_app/videos')),
                ('targetemotion', models.IntegerField(blank=True, db_column='targetemotion')),
                ('taskimage', models.ImageField(blank=True, db_column='image', null=True, upload_to='tale_app/pictures')),
                ('tasktext', models.CharField(blank=True, db_column='name', max_length=128, null=True)),
                ('type', models.IntegerField(db_column='type')),
                ('order', models.IntegerField(db_column='order')),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Tale',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=128, null=True)),
                ('image', models.ImageField(blank=True, db_column='image', upload_to='tale_app/pictures')),
                ('level', models.IntegerField(db_column='level')),
            ],
            options={
                'db_table': 'tale',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='taleid',
            field=models.ForeignKey(db_column='taleid', on_delete=django.db.models.deletion.CASCADE, to='tale_app.Tale'),
        ),
    ]
