# Generated by Django 2.1.13 on 2019-10-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tale_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiIcons',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('primaryid', models.IntegerField(db_column='primaryid')),
                ('emotionid', models.IntegerField(db_column='emotionid')),
                ('image', models.ImageField(db_column='image', upload_to='tale_app/pictures')),
            ],
            options={
                'db_table': 'emojiicons',
            },
        ),
    ]
