# Generated by Django 2.1.13 on 2019-10-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tale_app', '0002_emojiicons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmojiIcons',
            new_name='EmojiIcon',
        ),
    ]
